apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: example
        resources:
          limits:
            memory: 1000M
            cpu: 1000m
          requests:
            memory: 50M
            cpu: 50m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:9.5.0
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: restdb
        - name: MYSQL_USER
          value: restadmin
        - name: MYSQL_PASSWORD
          value: password
        resources:
          limits:
            memory: 1000M
            cpu: 1000m
          requests:
            memory: 50M
            cpu: 50m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-server
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - image: spring7authserver:0.0.1-SNAPSHOT
        name: auth-server
        resources:
          limits:
            memory: 1000M
            cpu: 1000m
          requests:
            memory: 50M
            cpu: 50m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rest-mvc
  name: rest-mvc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-mvc
  template:
    metadata:
      labels:
        app: rest-mvc
    spec:
      containers:
      - image: spring7restmvc:0.0.1-SNAPSHOT
        name: rest-mvc
        env:
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
          value: http://auth-server:9000
        - name: SPRING_PROFILES_ACTIVE
          value: localmysql
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/restdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        resources:
          limits:
            memory: 1000M
            cpu: 1000m
          requests:
            memory: 50M
            cpu: 50m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reactive
  name: reactive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reactive
  template:
    metadata:
      labels:
        app: reactive
    spec:
      containers:
      - image: spring7reactive:0.0.1-SNAPSHOT
        name: reactive
        env:
        - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI
          value: http://auth-server:9000
        - name: SERVER_PORT
          value: "8080"
        resources:
          limits:
            memory: 1000M
            cpu: 1000m
          requests:
            memory: 50M
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-server
  name: auth-server
spec:
  ports:
  - name: auth-server
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: auth-server
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest-mvc
  name: rest-mvc
spec:
  ports:
  - name: rest-mvc
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: rest-mvc
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: reactive
  name: reactive
spec:
  ports:
  - name: reactive
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: reactive
  type: ClusterIP
status:
  loadBalancer: {}
